import { Calendar, PackageX, ShoppingCart, Wallet } from "lucide-react";
import { StoreStatus } from "../enums/store-status.enum";

export const ProductCategoryData = [
  {
    id: "cat1",
    name: "Action Figures",
  },
  {
    id: "cat2",
    name: "Dolls",
  },
];

export const StaffFakeData = [
  {
    id: "staff-1",
    fullName: "Nguyễn Ngọc Thạch",
    email: "thach.nguyen",
    role: "Manager",
    status: "active",
  },
  {
    id: "staff-2",
    fullName: "Trần Minh Quân",
    email: "minhquan.tran",
    role: "Cashier",
    status: "active",
  },
  {
    id: "staff-3",
    fullName: "Lê Thị Hồng",
    email: "hong.le",
    role: "Staff",
    status: "inactive",
  },
  {
    id: "staff-4",
    fullName: "Phạm Quốc Bảo",
    email: "quocbao.pham",
    role: "Staff",
    status: "pending",
  },
  {
    id: "staff-5",
    fullName: "Võ Anh Tuấn",
    email: "anhtuan.vo",
    role: "Supervisor",
    status: "active",
  },
];

export const ReportFakeData = [
  {
    id: "report-1",
    store: "London Branch",
    staff: "Nguyễn Ngọc Thạch",
    createdAt: "2026-01-02",
  },
  {
    id: "report-2",
    store: "Manchester Branch",
    staff: "Trần Minh Quân",
    createdAt: "2026-01-03",
  },
  {
    id: "report-3",
    store: "Birmingham Branch",
    staff: "Lê Thị Hồng",
    createdAt: "2026-01-04",
  },
  {
    id: "report-4",
    store: "Liverpool Branch",
    staff: "Phạm Quốc Bảo",
    createdAt: "2026-01-05",
  },
  {
    id: "report-5",
    store: "Leeds Branch",
    staff: "Võ Anh Tuấn",
    createdAt: "2026-01-06",
  },
  {
    id: "report-6",
    store: "London Branch",
    staff: "Trần Minh Quân",
    createdAt: "2026-01-07",
  },
  {
    id: "report-7",
    store: "Manchester Branch",
    staff: "Nguyễn Ngọc Thạch",
    createdAt: "2026-01-08",
  },
  {
    id: "report-8",
    store: "Birmingham Branch",
    staff: "Phạm Quốc Bảo",
    createdAt: "2026-01-09",
  },
  {
    id: "report-9",
    store: "Liverpool Branch",
    staff: "Lê Thị Hồng",
    createdAt: "2026-01-10",
  },
  {
    id: "report-10",
    store: "Leeds Branch",
    staff: "Võ Anh Tuấn",
    createdAt: "2026-01-11",
  },
];

export const StoreFakeData = [
  {
    id: "store1",
    name: "ToyCabin Downtown",
    latitude: 10.7769,
    longitude: 106.7009,
    address: "123 Main St, District 1, HCMC",
    rating: 4.5,
    images: ["https://picsum.photos/200/300?random=1"],
    openTime: "08:00",
    closeTime: "22:00",
    openDay: "Mon - Sun",
    status: StoreStatus.ACTIVE,
  },
  {
    id: "store2",
    name: "ToyCabin Saigon Centre",
    latitude: 10.7731,
    longitude: 106.6983,
    rating: 4.5,
    address: "65 Le Loi, District 1, HCMC",
    images: ["https://picsum.photos/200/300?random=2"],
    openTime: "08:00",
    closeTime: "22:00",
    openDay: "Mon - Sun",
    status: StoreStatus.ACTIVE,
  },
  {
    id: "store3",
    name: "ToyCabin Ben Thanh",
    latitude: 10.7725,
    longitude: 106.698,
    rating: 4.5,
    address: "Ben Thanh Market, District 1, HCMC",
    images: ["https://picsum.photos/200/300?random=3"],
    openTime: "08:00",
    closeTime: "22:00",
    openDay: "Mon - Sun",
    status: StoreStatus.INACTIVE,
  },
  {
    id: "store4",
    name: "ToyCabin Phu Nhuan",
    latitude: 10.799,
    longitude: 106.6786,
    rating: 4.5,
    address: "12 Nguyen Van Troi, Phu Nhuan, HCMC",
    images: ["https://picsum.photos/200/300?random=4"],
    openTime: "08:00",
    closeTime: "22:00",
    openDay: "Mon - Sun",
    status: StoreStatus.ACTIVE,
  },
  {
    id: "store5",
    name: "ToyCabin Tan Binh",
    latitude: 10.8018,
    longitude: 106.652,
    rating: 4.5,
    address: "20 Truong Son, Tan Binh, HCMC",
    images: ["https://picsum.photos/200/300?random=5"],
    openTime: "08:00",
    closeTime: "22:00",
    openDay: "Mon - Sun",
    status: StoreStatus.ACTIVE,
  },
  {
    id: "store6",
    name: "ToyCabin Go Vap",
    latitude: 10.8389,
    longitude: 106.6658,
    rating: 4.5,
    address: "45 Quang Trung, Go Vap, HCMC",
    images: ["https://picsum.photos/200/300?random=6"],
    openTime: "08:00",
    closeTime: "22:00",
    openDay: "Mon - Sun",
    status: StoreStatus.CLOSED,
  },
  {
    id: "store7",
    name: "ToyCabin Binh Thanh",
    latitude: 10.8032,
    longitude: 106.7124,
    rating: 4.5,
    address: "90 Dien Bien Phu, Binh Thanh, HCMC",
    images: ["https://picsum.photos/200/300?random=7"],
    openTime: "08:00",
    closeTime: "22:00",
    openDay: "Mon - Sun",
    status: StoreStatus.ACTIVE,
  },
  {
    id: "store8",
    name: "ToyCabin District 7",
    latitude: 10.7296,
    longitude: 106.7217,
    rating: 4.5,
    address: "88 Nguyen Van Linh, District 7, HCMC",
    images: ["https://picsum.photos/200/300?random=8"],
    openTime: "08:00",
    closeTime: "22:00",
    openDay: "Mon - Sun",
    status: StoreStatus.ACTIVE,
  },
  {
    id: "store9",
    name: "ToyCabin Thu Duc",
    latitude: 10.8493,
    longitude: 106.7537,
    rating: 4.5,
    address: "15 Vo Van Ngan, Thu Duc, HCMC",
    images: ["https://picsum.photos/200/300?random=9"],
    openTime: "08:00",
    closeTime: "22:00",
    openDay: "Mon - Sun",
    status: StoreStatus.ACTIVE,
  },
  {
    id: "store10",
    name: "ToyCabin Binh Tan",
    latitude: 10.7652,
    longitude: 106.6039,
    rating: 4.5,
    address: "200 Kinh Duong Vuong, Binh Tan, HCMC",
    images: ["https://picsum.photos/200/300?random=10"],
    openTime: "08:00",
    closeTime: "22:00",
    openDay: "Mon - Sun",
    status: StoreStatus.ACTIVE,
  },
  {
    id: "store11",
    name: "ToyCabin Tan Phu",
    latitude: 10.7903,
    longitude: 106.6285,
    rating: 4.5,
    address: "30 Au Co, Tan Phu, HCMC",
    images: ["https://picsum.photos/200/300?random=11"],
    openTime: "08:00",
    closeTime: "22:00",
    openDay: "Mon - Sun",
    status: StoreStatus.ACTIVE,
  },
];

export const OWNER_OPTION = [{ value: "1", label: "A" }];

export const StoreDetailStatCard = [
  {
    id: 1,
    name: "Total Orders",
    value: 2487,
    icon: ShoppingCart,
    color: "blue",
    trend: 22.7,
  },
  {
    id: 2,
    name: "Monthly Orders",
    value: 486,
    icon: Calendar,
    color: "purple",
    trend: -8.32,
  },
  {
    id: 3,
    name: "Monthly Revenue",
    value: "$41,789",
    icon: Wallet,
    color: "red",
    trend: 16.8,
  },
  {
    id: 4,
    name: "Out Of Stock",
    value: "44 Items",
    icon: PackageX,
    color: "yellow",
  },
];
